version: '3.5'
services:
  php:
    container_name: movies
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    container_name: "postgres"
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=M0v13s
    ports:
      - 5432:5432